# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.search.v1 import search_pb2 as contracts_dot_search_dot_v1_dot_search__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/search/v1/search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchStub:
    """Hybrid (vector + BM25, fused with RRF) search over Obsidian notes. Served over gRPC by search/
    (see docs/decisions/0005-grpc-generated-clients.md); callers use contracts.search.SearchClient.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/search.v1.Search/Query',
                request_serializer=contracts_dot_search_dot_v1_dot_search__pb2.QueryRequest.SerializeToString,
                response_deserializer=contracts_dot_search_dot_v1_dot_search__pb2.QueryResponse.FromString,
                _registered_method=True)


class SearchServicer:
    """Hybrid (vector + BM25, fused with RRF) search over Obsidian notes. Served over gRPC by search/
    (see docs/decisions/0005-grpc-generated-clients.md); callers use contracts.search.SearchClient.
    """

    def Query(self, request, context):
        """INVALID_ARGUMENT if `query` is empty, `k` is outside 0 to 50 or `collection` is not indexed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=contracts_dot_search_dot_v1_dot_search__pb2.QueryRequest.FromString,
                    response_serializer=contracts_dot_search_dot_v1_dot_search__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.v1.Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.v1.Search', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Search:
    """Hybrid (vector + BM25, fused with RRF) search over Obsidian notes. Served over gRPC by search/
    (see docs/decisions/0005-grpc-generated-clients.md); callers use contracts.search.SearchClient.
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.v1.Search/Query',
            contracts_dot_search_dot_v1_dot_search__pb2.QueryRequest.SerializeToString,
            contracts_dot_search_dot_v1_dot_search__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
