# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/search/v1/search.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'contracts/search/v1/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n contracts/search/v1/search.proto\x12\tsearch.v1\"<\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x12\n\ncollection\x18\x03 \x01(\t\"3\n\rQueryResponse\x12\"\n\x07results\x18\x01 \x03(\x0b\x32\x11.search.v1.Result\"X\n\x06Result\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\nsimilarity\x18\x04 \x01(\x01\x12\x0c\n\x04\x62m25\x18\x05 \x01(\x01\x32\x44\n\x06Search\x12:\n\x05Query\x12\x17.search.v1.QueryRequest\x1a\x18.search.v1.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.search.v1.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=47
  _globals['_QUERYREQUEST']._serialized_end=107
  _globals['_QUERYRESPONSE']._serialized_start=109
  _globals['_QUERYRESPONSE']._serialized_end=160
  _globals['_RESULT']._serialized_start=162
  _globals['_RESULT']._serialized_end=250
  _globals['_SEARCH']._serialized_start=252
  _globals['_SEARCH']._serialized_end=320
# @@protoc_insertion_point(module_scope)
