# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contracts/agent/v1/agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'contracts/agent/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ontracts/agent/v1/agent.proto\x12\x08\x61gent.v1\"1\n\nRunRequest\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.agent.v1.Message\"8\n\x07Message\x12\x1c\n\x04role\x18\x01 \x01(\x0e\x32\x0e.agent.v1.Role\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"_\n\x08RunEvent\x12&\n\x08progress\x18\x01 \x01(\x0b\x32\x12.agent.v1.ProgressH\x00\x12\"\n\x06\x61nswer\x18\x02 \x01(\x0b\x32\x10.agent.v1.AnswerH\x00\x42\x07\n\x05\x65vent\"\x18\n\x08Progress\x12\x0c\n\x04tick\x18\x01 \x01(\x05\"\x16\n\x06\x41nswer\x12\x0c\n\x04text\x18\x01 \x01(\t*P\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bROLE_SYSTEM\x10\x01\x12\r\n\tROLE_USER\x10\x02\x12\x12\n\x0eROLE_ASSISTANT\x10\x03\x32:\n\x05\x41gent\x12\x31\n\x03Run\x12\x14.agent.v1.RunRequest\x1a\x12.agent.v1.RunEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts.agent.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=300
  _globals['_ROLE']._serialized_end=380
  _globals['_RUNREQUEST']._serialized_start=44
  _globals['_RUNREQUEST']._serialized_end=93
  _globals['_MESSAGE']._serialized_start=95
  _globals['_MESSAGE']._serialized_end=151
  _globals['_RUNEVENT']._serialized_start=153
  _globals['_RUNEVENT']._serialized_end=248
  _globals['_PROGRESS']._serialized_start=250
  _globals['_PROGRESS']._serialized_end=274
  _globals['_ANSWER']._serialized_start=276
  _globals['_ANSWER']._serialized_end=298
  _globals['_AGENT']._serialized_start=382
  _globals['_AGENT']._serialized_end=440
# @@protoc_insertion_point(module_scope)
