# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.agent.v1 import agent_pb2 as contracts_dot_agent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/agent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub:
    """The agent loop (decide, retrieve, grade, generate, judge) as a service. Served over gRPC by
    agent/ (see docs/decisions/0005-grpc-generated-clients.md); the orchestrator calls it through
    contracts.agent.AgentClient. Stateless: every call carries the whole conversation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/agent.v1.Agent/Run',
                request_serializer=contracts_dot_agent_dot_v1_dot_agent__pb2.RunRequest.SerializeToString,
                response_deserializer=contracts_dot_agent_dot_v1_dot_agent__pb2.RunEvent.FromString,
                _registered_method=True)


class AgentServicer:
    """The agent loop (decide, retrieve, grade, generate, judge) as a service. Served over gRPC by
    agent/ (see docs/decisions/0005-grpc-generated-clients.md); the orchestrator calls it through
    contracts.agent.AgentClient. Stateless: every call carries the whole conversation.
    """

    def Run(self, request, context):
        """Answers the conversation. While the loop works the stream sends a `Progress` event every few
        seconds, then exactly one `Answer` and ends. Intermediate drafts are never sent.
        INVALID_ARGUMENT if `messages` is empty; UNAVAILABLE if a dependency (search, OpenRouter)
        failed; anything else is INTERNAL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=contracts_dot_agent_dot_v1_dot_agent__pb2.RunRequest.FromString,
                    response_serializer=contracts_dot_agent_dot_v1_dot_agent__pb2.RunEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent:
    """The agent loop (decide, retrieve, grade, generate, judge) as a service. Served over gRPC by
    agent/ (see docs/decisions/0005-grpc-generated-clients.md); the orchestrator calls it through
    contracts.agent.AgentClient. Stateless: every call carries the whole conversation.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.v1.Agent/Run',
            contracts_dot_agent_dot_v1_dot_agent__pb2.RunRequest.SerializeToString,
            contracts_dot_agent_dot_v1_dot_agent__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
