"""Builds the `ml` service dashboard with the Grafana Foundation SDK and uploads it to Grafana.

    just observability grafana dashboard          # build, write dashboards/ml.json, upload
    just observability grafana dashboard --dry-run   # build and write only

It charts the shared operation metrics from ../src/observability/metrics.py: request count,
latency, and the three kinds of unsuccessful outcome (error, fault, failure), per operation; and
the run time of `@timed` functions (../src/observability/timing.py), per function.
Grafana is GRAFANA_URL (default http://localhost:3001), user GRAFANA_USER / GRAFANA_PASSWORD
(default admin / admin). Uploading again replaces the dashboard (same uid).
"""

import base64
import json
import os
import sys
import urllib.request
from pathlib import Path

from grafana_foundation_sdk.builders import common as common_builder
from grafana_foundation_sdk.builders import dashboard, prometheus, stat, timeseries
from grafana_foundation_sdk.cog.encoder import JSONEncoder
from grafana_foundation_sdk.models import common
from grafana_foundation_sdk.models.dashboard import (
    DataSourceRef,
    DynamicConfigValue,
    FieldColorModeId,
    VariableRefresh,
)

UID = "ml-operations"
OUT = Path(__file__).parent / "dashboards" / "ml.json"
PROMETHEUS = DataSourceRef(type_val="prometheus", uid="prometheus")  # provisioned by otel-lgtm

COUNT = "ml_operations_total"
BUCKET = "ml_operation_duration_seconds_bucket"
WHERE = 'job=~"$service", instance=~"$instance"'  # instance: the pod (service.instance.id)
SELECT = WHERE + ', operation=~"$operation"'
TIME_BUCKET = "ml_time_seconds_bucket"
TIME_COUNT = "ml_time_seconds_count"
OUTCOME_COLORS = {"success": "green", "error": "yellow", "fault": "orange", "failure": "red"}
OUTCOME_HELP = {
    "error": "The caller's mistake: 4xx, bad input, unknown route, wrong key.",
    "fault": "A modelled service failure: a dependency down or timing out (ServiceFault, deliberate 5xx).",
    "failure": "Unplanned: any other exception.",
}


def query(expr: str, legend: str = "", ref: str = "A") -> prometheus.Dataquery:
    return prometheus.Dataquery().expr(expr).legend_format(legend or "__auto").ref_id(ref)


def color(name: str) -> DynamicConfigValue:
    return DynamicConfigValue(id_val="color", value={"mode": "fixed", "fixedColor": name})


def total(outcome: str | None = None) -> str:
    match = f', outcome="{outcome}"' if outcome else ""
    return f"sum(increase({COUNT}{{{SELECT}{match}}}[$__range]))"


def stat_panel(title: str, expr: str, unit: str, description: str = "", tint: str = "blue"):
    return (stat.Panel().title(title).description(description).datasource(PROMETHEUS)
            .with_target(query(expr).instant()).unit(unit).height(4).span(4).no_value("0")
            .color_mode(common.BigValueColorMode.BACKGROUND)
            .graph_mode(common.BigValueGraphMode.NONE)
            .color_scheme(dashboard.FieldColor().mode(FieldColorModeId.FIXED).fixed_color(tint)))


def series_panel(title: str, unit: str, description: str = "", span: int = 12):
    return (timeseries.Panel().title(title).description(description).datasource(PROMETHEUS)
            .unit(unit).height(8).span(span).fill_opacity(10).line_width(1)
            .legend(common_builder.VizLegendOptions().display_mode(common.LegendDisplayMode.TABLE)
                    .placement(common.LegendPlacement.BOTTOM).show_legend(True)
                    .calcs(["mean", "max"])))


def per_minute(by: str, outcome: str | None = None) -> str:
    match = f', outcome="{outcome}"' if outcome else ""
    return f"60 * sum by ({by}) (rate({COUNT}{{{SELECT}{match}}}[$__rate_interval]))"


def quantile(q: float) -> str:
    return (f"histogram_quantile({q}, sum by (le, operation) "
            f"(rate({BUCKET}{{{SELECT}}}[$__rate_interval])))")


def variable(name: str, label: str, values: str) -> dashboard.QueryVariable:
    """A multi-select of label values, `All` by default."""
    return (dashboard.QueryVariable(name).label(label).datasource(PROMETHEUS).query(values)
            .multi(True).include_all(True).all_value(".*")
            .refresh(VariableRefresh.ON_TIME_RANGE_CHANGED))


def build() -> dict:
    d = (dashboard.Dashboard("ML operations").uid(UID).tags(["ml", "observability"])
         .description("Request count, latency, errors, faults and failures of every operation. "
                      "Generated by observability/grafana/dashboard.py; edit that, not the UI.")
         .time("now-6h", "now").refresh("30s").timezone("browser")
         .with_variable(variable("service", "Service", f"label_values({COUNT}, job)"))
         .with_variable(variable("instance", "Instance",
                                 f'label_values({COUNT}{{job=~"$service"}}, instance)'))
         .with_variable(variable("operation", "Operation",
                                 f'label_values({COUNT}{{{WHERE}}}, operation)')))

    d = (d.with_row(dashboard.Row("Overview (selected time range)"))
         .with_panel(stat_panel("Requests", total(), "short", "Operations finished in the range."))
         .with_panel(stat_panel("Success rate", f"{total('success')} / {total()}", "percentunit",
                                "Share of operations that succeeded.", "green"))
         .with_panel(stat_panel("Error rate", f"{total('error')} / {total()}", "percentunit",
                                OUTCOME_HELP["error"], "yellow"))
         .with_panel(stat_panel("Fault rate", f"{total('fault')} / {total()}", "percentunit",
                                OUTCOME_HELP["fault"], "orange"))
         .with_panel(stat_panel("Failure rate", f"{total('failure')} / {total()}", "percentunit",
                                OUTCOME_HELP["failure"], "red"))
         .with_panel(stat_panel(
             "p95 latency",
             f"histogram_quantile(0.95, sum by (le) (increase({BUCKET}{{{SELECT}}}[$__range])))",
             "s", "95% of operations finished faster than this.", "purple")))

    by_outcome = (series_panel("Requests per minute, by outcome", "short",
                               "Every operation, stacked by its outcome.")
                  .with_target(query(per_minute("outcome"), "{{outcome}}"))
                  .stacking(common_builder.StackingConfig().mode(common.StackingMode.NORMAL)))
    for outcome, c in OUTCOME_COLORS.items():
        by_outcome = by_outcome.override_by_name(outcome, [color(c)])
    d = (d.with_row(dashboard.Row("Traffic"))
         .with_panel(by_outcome)
         .with_panel(series_panel("Requests per minute, by operation", "short")
                     .with_target(query(per_minute("operation"), "{{operation}}"))))

    latency = series_panel("Latency p50 / p95 / p99, by operation", "s",
                           "From the ml.operation.duration histogram.", span=24)
    for i, q in enumerate((0.5, 0.95, 0.99)):
        latency = latency.with_target(query(quantile(q), f"p{int(q * 100)} {{{{operation}}}}", "ABC"[i]))
    d = d.with_row(dashboard.Row("Latency")).with_panel(latency)

    d = d.with_row(dashboard.Row("Errors, faults, failures"))
    for outcome in ("error", "fault", "failure"):
        d = d.with_panel(
            series_panel(f"{outcome.capitalize()}s per minute, by operation", "short",
                         OUTCOME_HELP[outcome], span=8)
            .with_target(query(per_minute("operation", outcome), "{{operation}}"))
            .color_scheme(dashboard.FieldColor().mode(FieldColorModeId.FIXED).fixed_color(OUTCOME_COLORS[outcome])))

    calls = (series_panel("Calls per minute, by function", "short",
                          "Calls of @timed functions.")
             .with_target(query(f'60 * sum by (function) (rate({TIME_COUNT}{{{WHERE}}}'
                                f'[$__rate_interval]))', "{{function}}")))
    time_p = series_panel("Run time p50 / p95, by function", "s",
                          "From the ml.time histogram of @timed functions.")
    for i, q in enumerate((0.5, 0.95)):
        time_p = time_p.with_target(query(
            f"histogram_quantile({q}, sum by (le, function) "
            f'(rate({TIME_BUCKET}{{{WHERE}}}[$__rate_interval])))',
            f"p{int(q * 100)} {{{{function}}}}", "AB"[i]))
    d = d.with_row(dashboard.Row("Function time")).with_panel(calls).with_panel(time_p)

    return json.loads(json.dumps(d.build(), cls=JSONEncoder))


def upload(model: dict) -> str:
    url = os.environ.get("GRAFANA_URL", "http://localhost:3001").rstrip("/")
    user = os.environ.get("GRAFANA_USER", "admin")
    password = os.environ.get("GRAFANA_PASSWORD", "admin")
    req = urllib.request.Request(
        f"{url}/api/dashboards/db", method="POST",
        data=json.dumps({"dashboard": model, "overwrite": True}).encode(),
        headers={"Content-Type": "application/json",
                 "Authorization": "Basic " + base64.b64encode(f"{user}:{password}".encode()).decode()})
    with urllib.request.urlopen(req) as res:
        return url + json.load(res)["url"]


if __name__ == "__main__":
    model = build()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(model, indent=2) + "\n")
    print(f"wrote {OUT}")
    if "--dry-run" not in sys.argv:
        print(f"uploaded: {upload(model)}")
